--- #YAML:1.0
name:               Catalyst-Model-Sedna
version:            0.004
abstract:           Access the Sedna XML Database
author:
    - Daniel Ruoso <daniel@ruoso.com>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Catalyst::Runtime:  5.8
    Moose:              0.9
    Sedna:              0.002
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.54
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
